title: Konsta Hasanen
#logo: /assets/img/headshot_circle.png
description: 
*Sähköposti:* konsta.hasanen@gmail.com
*LinkedIn:* [LinkedIn-profiili](https://www.linkedin.com/in/konsta-hasanen-945667222/)
#show_downloads: true
theme: jekyll-theme-minimal
